-- Settings Table
CREATE TABLE IF NOT EXISTS `settings` (
  `id` INT PRIMARY KEY DEFAULT 1,
  `site_name` VARCHAR(255) DEFAULT 'SurePredictor',
  `site_description` TEXT,
  `gemini_api_key` VARCHAR(255),
  `footer_text` TEXT,
  `contact_email` VARCHAR(255),
  `primary_color` VARCHAR(20) DEFAULT '#059669',
  `dark_mode` TINYINT(1) DEFAULT 0,
  `site_logo` VARCHAR(255),
  `site_icon` VARCHAR(255)
);

-- Insert default settings
INSERT IGNORE INTO `settings` (`id`, `site_name`, `site_description`) VALUES (1, 'SurePredictor', 'Global football insights powered by advanced AI.');

-- Admin Users Table
CREATE TABLE IF NOT EXISTS `admins` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(50) UNIQUE NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `last_login` DATETIME
);

-- Advertising Management Table
CREATE TABLE IF NOT EXISTS `ads` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `slot_name` VARCHAR(50) UNIQUE, -- 'header_top', 'mid_content', 'result_footer'
  `ad_code` TEXT,
  `is_active` BOOLEAN DEFAULT TRUE
);

-- Insert default ad slots
INSERT IGNORE INTO `ads` (`slot_name`, `ad_code`, `is_active`) VALUES
('header_top', '', 0),
('mid_content', '', 0),
('result_footer', '', 0);

-- Prediction Cache Table
CREATE TABLE IF NOT EXISTS `prediction_cache` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `match_hash` VARCHAR(64) UNIQUE,
  `home_team` VARCHAR(100),
  `away_team` VARCHAR(100),
  `result_json` LONGTEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SEO Settings Table
CREATE TABLE IF NOT EXISTS `seo_settings` (
  `id` INT PRIMARY KEY DEFAULT 1,
  `meta_title` VARCHAR(255),
  `meta_description` TEXT,
  `og_image` VARCHAR(255)
);

INSERT IGNORE INTO `seo_settings` (`id`, `meta_title`, `meta_description`) VALUES (1, 'SurePredictor - AI Football Predictions', 'Professional football insights and match forecasts generated by advanced AI.');
