<?php
$settings = getSettings($conn);
?>
    <footer class="mt-24 pt-8 border-t border-slate-100 dark:border-slate-800 text-center text-slate-400 text-sm">
        <p>© <?php echo date('Y'); ?> <?php echo $settings['site_name']; ?>. All predictions generated by Gemini AI.</p>
        <p class="mt-2 text-xs"><?php echo $settings['footer_text'] ?: 'Data dynamically calibrated for the current global football calendar.'; ?></p>
    </footer>

    <!-- PWA Installation Popup -->
    <div id="pwa-modal" class="fixed inset-0 bg-black/50 backdrop-blur-sm z-[100] hidden items-center justify-center p-4">
        <div class="bg-white dark:bg-slate-800 rounded-3xl p-8 max-w-sm w-full text-center shadow-2xl scale-90 transition-transform duration-300" id="pwa-content">
            <img src="<?php echo $settings['site_logo'] ?: 'assets/images/logo.png'; ?>" alt="Logo" class="h-20 w-20 mx-auto mb-6 rounded-2xl shadow-lg">
            <h3 class="text-2xl font-black mb-2">Install Our App</h3>
            <p class="text-slate-500 dark:text-slate-400 text-sm mb-8">Get the best sport predictions right on your home screen for quick access!</p>
            <div class="flex flex-col gap-3">
                <button id="pwa-install-btn" class="w-full py-4 bg-primary text-white font-bold rounded-2xl shadow-lg hover:opacity-90 transition-all">
                    Install Now
                </button>
                <button id="pwa-close-btn" class="w-full py-4 bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 font-bold rounded-2xl hover:bg-slate-200 dark:hover:bg-slate-600 transition-all">
                    Maybe Later
                </button>
            </div>
        </div>
    </div>

    <script>
        let deferredPrompt;
        const pwaModal = document.getElementById('pwa-modal');
        const pwaContent = document.getElementById('pwa-content');
        const installBtn = document.getElementById('pwa-install-btn');
        const closeBtn = document.getElementById('pwa-close-btn');

        window.addEventListener('beforeinstallprompt', (e) => {
            e.preventDefault();
            deferredPrompt = e;

            // Show modal after 3 seconds
            setTimeout(() => {
                pwaModal.classList.remove('hidden');
                pwaModal.classList.add('flex');
                setTimeout(() => pwaContent.classList.remove('scale-90'), 10);
            }, 3000);
        });

        installBtn.addEventListener('click', async () => {
            if (deferredPrompt) {
                deferredPrompt.prompt();
                const { outcome } = await deferredPrompt.userChoice;
                deferredPrompt = null;
                closePwaModal();
            }
        });

        closeBtn.addEventListener('click', closePwaModal);

        function closePwaModal() {
            pwaContent.classList.add('scale-90');
            setTimeout(() => {
                pwaModal.classList.add('hidden');
                pwaModal.classList.remove('flex');
            }, 300);
        }

        if ('serviceWorker' in navigator) {
            window.addEventListener('load', () => {
                navigator.serviceWorker.register('sw.js');
            });
        }
    </script>
</body>
</html>
